# Generated by Django 4.2.5 on 2024-01-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=18)),
                ('district', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('bike_id', models.IntegerField()),
                ('bike_name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=18)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
