# Generated by Django 4.2.5 on 2024-01-22 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('Bajaj', 'Bajaj'), ('Yamaha', 'Yamaha'), ('TVS', 'TVS'), ('Royal Enfield', 'Royal Enfield')], max_length=50)),
                ('color', models.CharField(max_length=255)),
                ('cc', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('fuel_capacity', models.IntegerField()),
                ('driven', models.IntegerField()),
                ('tyres_type', models.CharField(choices=[('Tube', 'Tube'), ('Tubeless', 'Tubeless')], max_length=50)),
                ('wheels_type', models.CharField(choices=[('Spoke', 'Spoke'), ('Alloy', 'Alloy')], max_length=50)),
                ('previous_owners', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField(max_length=2000)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=50)),
                ('district', models.CharField(choices=[('Bagerhat', 'Bagerhat'), ('Bandarban', 'Bandarban'), ('Barguna', 'Barguna'), ('Barisal', 'Barisal'), ('Bhola', 'Bhola'), ('Bogra', 'Bogra'), ('Brahmanbaria', 'Brahmanbaria'), ('Chandpur', 'Chandpur'), ('Chapai Nawabganj', 'Chapai Nawabganj'), ('Chattogram', 'Chattogram'), ('Chuadanga', 'Chuadanga'), ('Comilla', 'Comilla'), ("Cox's Bazar", "Cox's Bazar"), ('Dhaka', 'Dhaka'), ('Dinajpur', 'Dinajpur'), ('Faridpur', 'Faridpur'), ('Feni', 'Feni'), ('Gaibandha', 'Gaibandha'), ('Gazipur', 'Gazipur'), ('Gopalganj', 'Gopalganj'), ('Habiganj', 'Habiganj'), ('Jamalpur', 'Jamalpur'), ('Jashore', 'Jashore'), ('Jhalokathi', 'Jhalokathi'), ('Jhenaidah', 'Jhenaidah'), ('Joypurhat', 'Joypurhat'), ('Khagrachari', 'Khagrachari'), ('Khulna', 'Khulna'), ('Kishoreganj', 'Kishoreganj'), ('Kurigram', 'Kurigram'), ('Kushtia', 'Kushtia'), ('Lakshmipur', 'Lakshmipur'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Magura', 'Magura'), ('Manikganj', 'Manikganj'), ('Meherpur', 'Meherpur'), ('Moulvibazar', 'Moulvibazar'), ('Munshiganj', 'Munshiganj'), ('Mymensingh', 'Mymensingh'), ('Naogaon', 'Naogaon'), ('Narail', 'Narail'), ('Narayanganj', 'Narayanganj'), ('Narsingdi', 'Narsingdi'), ('Natore', 'Natore'), ('Nawabganj', 'Nawabganj'), ('Netrokona', 'Netrokona'), ('Nilphamari', 'Nilphamari'), ('Noakhali', 'Noakhali'), ('Pabna', 'Pabna'), ('Panchagarh', 'Panchagarh'), ('Patuakhali', 'Patuakhali'), ('Pirojpur', 'Pirojpur'), ('Rajbari', 'Rajbari'), ('Rajshahi', 'Rajshahi'), ('Rangamati', 'Rangamati'), ('Rangpur', 'Rangpur'), ('Satkhira', 'Satkhira'), ('Shariatpur', 'Shariatpur'), ('Sherpur', 'Sherpur'), ('Sirajganj', 'Sirajganj'), ('Sunamganj', 'Sunamganj'), ('Sylhet', 'Sylhet'), ('Tangail', 'Tangail')], max_length=50)),
                ('price', models.IntegerField()),
                ('bike_photo_1', models.ImageField(blank=True, upload_to='Photos/bikes/%y/%m/%d')),
                ('bike_photo_2', models.ImageField(blank=True, upload_to='Photos/bikes/%y/%m/%d')),
                ('bike_photo_3', models.ImageField(blank=True, upload_to='Photos/bikes/%y/%m/%d')),
                ('bike_photo_4', models.ImageField(blank=True, upload_to='Photos/bikes/%y/%m/%d')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
